# Build stage
FROM node:20-alpine AS build

ARG REACT_APP_API_KEY
ARG REACT_APP_BACKEND_URL

ENV REACT_APP_API_KEY=$REACT_APP_API_KEY
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 10000

CMD ["nginx", "-g", "daemon off;"]
