version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: DockerFile
      args:
        REACT_APP_API_KEY: ${REACT_APP_API_KEY}
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    ports:
      - "10000:10000"
    environment:
      - REACT_APP_API_KEY=${REACT_APP_API_KEY}
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}