name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
          
      - name: Install dependencies
        run: npm ci
        
      - name: Debug - Before build
        run: |
          echo "Before build - current directory contents:"
          ls -la
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Package.json scripts:"
          cat package.json | grep -A 10 '"scripts"'
        
      - name: Build with Next.js
        env:
          NEXT_PUBLIC_CAL_USERNAME: ${{ secrets.NEXT_PUBLIC_CAL_USERNAME }}
          NEXT_PUBLIC_CAL_EVENT_SLUG: ${{ secrets.NEXT_PUBLIC_CAL_EVENT_SLUG }}
        run: |
          echo "Starting build..."
          npm run build
          echo "Build command completed with exit code: $?"
        
      - name: Debug - After build
        run: |
          echo "After build - current directory contents:"
          ls -la
          echo "Looking for output directories:"
          find . -name "out" -type d || echo "No 'out' directory found"
          find . -name ".next" -type d || echo "No '.next' directory found"
          echo "Contents of .next (if exists):"
          ls -la .next/ || echo ".next directory does not exist"
          echo "Contents of out (if exists):"
          ls -la out/ || echo "out directory does not exist"
          
      - name: Create out directory if missing
        run: |
          if [ ! -d "out" ]; then
            echo "out directory missing, checking for .next/standalone or other outputs..."
            if [ -d ".next" ]; then
              echo "Found .next directory, copying static files..."
              mkdir -p out
              if [ -d ".next/static" ]; then
                cp -r .next/static out/
              fi
              if [ -d ".next/standalone" ]; then
                cp -r .next/standalone/* out/
              fi
            else
              echo "No build output found, creating empty out directory"
              mkdir -p out
              echo "<h1>Build Error</h1><p>No static files were generated</p>" > out/index.html
            fi
          fi
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4